import skillArray from './skills'

import thissite from '../images/proj-imgs/ThisSite.png'
import linkedin from '../images/proj-imgs/LinkedInSearchExtension.png'
import projdefault from '../images/proj-imgs/projDefault.png'
import react from '../images/proj-imgs/ReactAWS.png'
import python from '../images/proj-imgs/PythonPreprocess.png'
import redis from '../images/proj-imgs/RedisCache.png'
import bpb from '../images/exp-logos/byte+bit.png'

const projects = [
  {
    name: 'This Site!',
    techs: [
      skillArray[1], skillArray[2], skillArray[5], skillArray[6], skillArray[10], skillArray[11], skillArray[17], skillArray[19]
    ],
    type: 'Solo Project',
    days: 10,
    desc: 'This counts right? I adapted it from ~3 year old code, upgraded to Typescript, added linting and tests, imported a Python chart,... the list goes on. All of the details are in the README.',
    github: 'https://github.com/PeterPCW/PeterPCW.github.io',
    page: 'https://peterpcw.github.io/',
    images: [
      { img: thissite, desc: "That's me!" }
    ],
    isActive: 'is-active'
  },
  {
    name: 'LinkedIn Search Extension',
    techs: [
      skillArray[1], skillArray[2], skillArray[5], skillArray[10], skillArray[11], skillArray[17], skillArray[18]
    ],
    type: 'Solo Project',
    days: 1,
    desc: 'A chrome extension to quickly launch a LinkedIn search. v1 is for job hunting and finding connections at the companies. v2 might upgrade this to an email lead gen SaaS product. 👀',
    github: 'https://github.com/PeterPCW/LinkedIn-Search-From-Anywhere',
    page: 'https://github.com/PeterPCW/LinkedIn-Search-From-Anywhere',
    images: [
      { img: linkedin, desc: 'Extension Popup' }
    ],
    isActive: ''
  },
  {
    name: 'GPT Technical Interviews',
    techs: [
      skillArray[15]
    ],
    type: 'Solo Project',
    days: 3,
    desc: 'A series of technical interview questions and answers generated by ChatGPT. I initially used these for studying and then realized that no one asks questions this hard. 😅',
    github: 'https://github.com/PeterPCW/GPT-Technical-Interviews',
    page: 'https://github.com/PeterPCW/GPT-Technical-Interviews',
    images: [
      { img: react, desc: 'React Frontend AWS' },{ img: python, desc: 'Scikit-learn Proprocess Data' },{ img: redis, desc: 'Node Redis Timed Cache' }
    ],
    isActive: ''
  },
  {
    name: 'Prompt Saver Extension',
    techs: [
      skillArray[1], skillArray[2], skillArray[5], skillArray[10], skillArray[11], skillArray[15], skillArray[17], skillArray[18]
    ],
    type: 'Solo Project',
    days: 5,
    desc: 'A chrome extension to save prompts found online. It connects with OpenAI API to test them if desired, but the point is to quickly save responses. Updated to the chat completion with the 3.5 API available. This still needs some work to update from the original narrower use case so no image yet.',
    github: 'https://github.com/PeterPCW/promptSaver',
    page: 'https://github.com/PeterPCW/promptSaver',
    images: [
      { img: projdefault, desc: 'No images yet' }
    ],
    isActive: ''
  },
  {
    name: 'Byte+Bit Site',
    techs: [
      skillArray[1], skillArray[2], skillArray[3], skillArray[4], skillArray[5], skillArray[6], skillArray[8], skillArray[10], skillArray[11], skillArray[12], skillArray[17], skillArray[19]
    ],
    type: 'Solo Project',
    days: 10,
    desc: 'Shrouded in mystery, this site is not ready to show just yet. It will be an example of a full-stack site using microservices architecture and hosted on AWS. This is where I will host and advertize SaaS products once they reach monetizable quality. Stay tuned!',
    github: '',
    page: '',
    images: [
      { img: bpb, desc: 'Old icon, might need a Designer' }
    ],
    isActive: ''
  },
]

export default projects